# Generated by Django 5.0.3 on 2024-06-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPatients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_naissance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
