# Generated by Django 5.0.3 on 2024-06-07 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPatients', '0005_alter_rendezvous_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_doctor': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
